### ISSUE TITLE
final project submission

### ISSUE THREAD

**Issue by pooja61096** [QMSS-G5072-2020/final_project_patel_pooja#1]
https://github.com/QMSS-G5072-2020/final_project_patel_pooja/commit/46a7226a2d775dd36099679c4801b3542b58d714

@SUN-Wenjun @lonadai0121

**Comment by lonadai0121** [comment]
3/5 Satisfactory Project: lack of complexity and breadth in skills; should not include your own API key in your package
3/3 well commented 
3/3 The code is efficient, correct, and minimal
3/3 The package structure is clear, easy to follow, and closely matches the structure discussed in class.
2/3 Documentation of the package and its contents is largely absent.
3/3 The package installs without problems.
1/3 Testing for the package is largely absent.
